name: Action Test

on:
  schedule:
           # ┌───────────── 分 (0 - 59)
           # │ ┌─────────────── 時間 (0 - 23)
           # │ │    ┌───────────── 日 (1 - 31)
           # │ │    │ ┌───────────── 月 (1 - 12 または JAN-DEC)
           # │ │    │ │ ┌───────────── 曜日 (0 - 6 または SUN-SAT)
           # │ │    │ │ │
           # │ │    │ │ │
           # │ │    │ │ │
    - cron: "13 * * * *"

jobs:
  numpy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r test/requirements.txt
      - name: Run Python
        run: python test/test.py
